<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsFormsImplicitUsings>false</EnableWindowsFormsImplicitUsings>
    <RootNamespace>Vrinfo.Mail.App</RootNamespace>
    <AssemblyName>VRINFO.Mail</AssemblyName>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
    <ApplicationTitle>VRINFO Mail</ApplicationTitle>
    <ServerGarbageCollection>false</ServerGarbageCollection>
    <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
    <RetainVMGarbageCollection>false</RetainVMGarbageCollection>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Vrinfo.Mail.Core\Vrinfo.Mail.Core.csproj" />
    <ProjectReference Include="..\Vrinfo.Mail.Imap\Vrinfo.Mail.Imap.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3351.48" />
  </ItemGroup>
  <ItemGroup>
            <None Include="Assets\**\*.*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
