<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Vrinfo.Mail.Imap</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Vrinfo.Mail.Core\Vrinfo.Mail.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.15.1" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.0" />
  </ItemGroup>
</Project>
